#建立表
CREATE TABLE S(
	SNO VARCHAR(3) PRIMARY KEY,
	SNAME VARCHAR(12) NOT NULL,
	SADDR VARCHAR(12) NOT NULL
);
CREATE INDEX ST ON S(SNO);

CREATE TABLE P(
	PNO VARCHAR(3) PRIMARY KEY,
	PNAME VARCHAR(12) NOT NULL,
	PCLR VARCHAR(12) NOT NULL
);
CREATE INDEX PT ON P(PNO);

CREATE TABLE J(
	JNO VARCHAR(3) PRIMARY KEY,
	JNAME VARCHAR(12) NOT NULL,
	JADDR VARCHAR(12) NOT NULL
);
CREATE INDEX JT ON J(JNO);


CREATE TABLE SPJ(
	SNO VARCHAR(3) NOT NULL,#PRIMARY KEY,
	PNO VARCHAR(3) NOT NULL,
	JNO VARCHAR(3) NOT NULL
);
CREATE INDEX SPJT ON SPJ(SNO);


#DROP TABLE S;
#DROP TABLE P;
#DROP TABLE J;


#插入数据
#1)
INSERT INTO S VALUES('S1', 'DIANZI', 'A');
INSERT INTO S VALUES('S2', 'JINGGUAN', 'B');
INSERT INTO S VALUES('S3', 'MEIYUAN', 'C');
INSERT INTO S VALUES('S4', 'JIKE', 'D');
INSERT INTO S VALUES('S5', 'SHUILI', 'A');

#2)	
INSERT INTO P VALUES('P1', 'LJ1', 'GREEN');
INSERT INTO P VALUES('P2', 'LJ2', 'WHITE');
INSERT INTO P VALUES('P3', 'LJ3', 'RED');
INSERT INTO P VALUES('P4', 'LJ4', 'BLUE');
INSERT INTO P VALUES('P4', 'LJ5', 'RED');

#3)
INSERT INTO J VALUES('J1', 'GC1', 'C');
INSERT INTO J VALUES('J2', 'GC2', 'A');
INSERT INTO J VALUES('J3', 'GC3', 'D');
INSERT INTO J VALUES('J4', 'GC4', 'A');

#4)
INSERT INTO SPJ VALUES('S1','LJ1','GC1');
INSERT INTO SPJ VALUES('S1','LJ2','GC2');
INSERT INTO SPJ VALUES('S1','LJ1','GC3');
INSERT INTO SPJ VALUES('S1','LJ4','GC4');
INSERT INTO SPJ VALUES('S2','LJ1','GC3');
INSERT INTO SPJ VALUES('S2','LJ2','GC3');
INSERT INTO SPJ VALUES('S2','LJ3','GC3');
INSERT INTO SPJ VALUES('S2','LJ4','GC3');
INSERT INTO SPJ VALUES('S2','LJ5','GC3');
INSERT INTO SPJ VALUES('S2','LJ5','GC4');
INSERT INTO SPJ VALUES('S3','LJ3','GC2');
INSERT INTO SPJ VALUES('S3','LJ5','GC4');
INSERT INTO SPJ VALUES('S3','LJ2','GC3');
INSERT INTO SPJ VALUES('S4','LJ4','GC2');
INSERT INTO SPJ VALUES('S4','LJ3','GC3');
INSERT INTO SPJ VALUES('S4','LJ2','GC1');
INSERT INTO SPJ VALUES('S5','LJ1','GC1');

#SELECT语句查询：
#(1)
SELECT DISTINCT S.SNAME
FROM SPJ,S
WHERE SPJ.JNO = '某项工程编号按钮'
AND SPJ.SNO = S.SNO;

#(2)
SELECT DISTINCT J.JNAME
FROM SPJ,J
WHERE SPJ.SNO = '某供应商编号按钮'
AND SPJ.JNO = J.JNO;

#(3)
SELECT DISTINCT J.JNAME
FROM SPJ,J,P
WHERE P.PCLR = 'RED'
AND P.PNO = SPJ.PNO
AND J.JNO = SPJ.JNO;

#(4)
SELECT S.SNAME
FROM S,P,J,SPJ
WHERE S.SADDR = 'A'
AND J.JADDR != 'A'
AND P.PCLR != 'RED'
AND S.SNO = SPJ.SNO
AND P.JNO = SPJ.JNO
AND J.JNO = SPJ.JNO;

#(5)
SELECT J.JNAME
FROM J
WHERE NOT EXISTS
(	SELECT * 
	FROM SPJ A
	WHERE A.SNO = '某供应商编号按钮'
	AND NOT EXISTS
	(	SELECT *
		FROM SPJ B
		WHERE B.JNO = J.JNO
		AND B.PNO = A.PNO
	)
);



#设计按钮的代码
#1
sqlStr := 'select DISTINCT SNAME’+
‘ from S,SPJ ‘+
‘where S.SNO=SPJ.SNO AND JNO= ''' + ComboBox1.Text + '''';

#2
sqlStr := 'select DISTINCT JNAME’+
‘ from J,SPJ ‘+
‘where J.JNO=SPJ.JNO AND SNO= ''' + cbb1.Text + '''';

#3
sqlStr := 'select DISTINCT JNAME’+
‘ from P,J,SPJ ‘+
‘where J.JNO=SPJ.JNO AND P.PNO=SPJ.PNO AND P.COLOR=''RED'' ';

#4
sqlStr := 'select DISTINCT SNAME’+
‘ from P,S,J,SPJ’+
‘ where J.JNO=SPJ.JNO AND S.SNO=SPJ.SNO’+
‘ AND P.PNO=SPJ.PNO AND S.CITY=''A'' ‘+
‘AND J.CITY!=''A'' AND COLOR!=''RED'' ';

#5
sqlStr := 'SELECT  JNAME'+
    ' FROM J A '+
    'WHERE NOT EXISTS '+
    '( SELECT * '+
    'FROM SPJ B'+
    ' WHERE B.SNO=''' + cbb1.Text + ''' AND NOT EXISTS '+
    '(SELECT * '+
    'FROM SPJ C '+
'WHERE C.JNO=A.JNO AND C.PNO=B.PNO))';

