#CA->CG
set_property PACKAGE_PIN W5 [get_ports sysclk]
set_property PACKAGE_PIN W13 [get_ports modecontrol]
set_property PACKAGE_PIN V16 [get_ports {testmode[1]}]
set_property PACKAGE_PIN V17 [get_ports {testmode[0]}]
set_property PACKAGE_PIN V14 [get_ports highfreq]
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property PACKAGE_PIN V7 [get_ports {Cathodes[7]}]
set_property PACKAGE_PIN W7 [get_ports {Cathodes[6]}]
set_property PACKAGE_PIN W6 [get_ports {Cathodes[5]}]
set_property PACKAGE_PIN U8 [get_ports {Cathodes[4]}]
set_property PACKAGE_PIN V8 [get_ports {Cathodes[3]}]
set_property PACKAGE_PIN U5 [get_ports {Cathodes[2]}]
set_property PACKAGE_PIN V5 [get_ports {Cathodes[1]}]
set_property PACKAGE_PIN U7 [get_ports {Cathodes[0]}]


create_clock -period 10.000 -name CLK -waveform {0.000 5.000} [get_ports sysclk]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
set_property IOSTANDARD LVCMOS33 [get_ports modecontrol]
set_property IOSTANDARD LVCMOS33 [get_ports {testmode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {testmode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports highfreq]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cathodes[0]}]