set_property PACKAGE_PIN U18 [get_ports reset]
set_property PACKAGE_PIN W5  [get_ports sysclk]

set_property PACKAGE_PIN B18  [get_ports UART_RX]
set_property PACKAGE_PIN A18  [get_ports UART_TX]

set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U16 [get_ports {led[0]}]

set_property PACKAGE_PIN W13 [get_ports {switch[7]}]
set_property PACKAGE_PIN W14 [get_ports {switch[6]}]
set_property PACKAGE_PIN V15 [get_ports {switch[5]}]
set_property PACKAGE_PIN W15 [get_ports {switch[4]}]
set_property PACKAGE_PIN W17 [get_ports {switch[3]}]
set_property PACKAGE_PIN W16 [get_ports {switch[2]}]
set_property PACKAGE_PIN V16 [get_ports {switch[1]}]
set_property PACKAGE_PIN V17 [get_ports {switch[0]}]

set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property PACKAGE_PIN V7 [get_ports {digital[7]}]
set_property PACKAGE_PIN U7 [get_ports {digital[6]}]
set_property PACKAGE_PIN V5 [get_ports {digital[5]}]
set_property PACKAGE_PIN U5 [get_ports {digital[4]}]
set_property PACKAGE_PIN V8 [get_ports {digital[3]}]
set_property PACKAGE_PIN U8 [get_ports {digital[2]}]
set_property PACKAGE_PIN W6 [get_ports {digital[1]}]
set_property PACKAGE_PIN W7 [get_ports {digital[0]}]


create_clock -period 10.000 -name CLK -waveform {0.000 5.000} [get_ports sysclk]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digital[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
